package com.wusuiwei.crowdfunding.entity;

import lombok.Data;

/**
 * This class was generated by MyBatis Generator.
 * 表名：t_admin
 * 表注释：管理员表
 */
@Data
public class Admin {
    /**
    * ID
    */
    private Integer id;

    /**
    * 账号
    */
    private String account;

    /**
    * 密码
    */
    private String password;
}