package com.wusuiwei.crowdfunding.generator;

import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.dom.java.Field;
import org.mybatis.generator.api.dom.java.TopLevelClass;
import org.mybatis.generator.internal.DefaultCommentGenerator;

public class CommentGenerator extends DefaultCommentGenerator {

    public CommentGenerator() {
        super();
    }

    @Override
    public void addFieldComment(Field field, IntrospectedTable introspectedTable, IntrospectedColumn introspectedColumn) {
        field.addJavaDocLine("/**");
        field.addJavaDocLine("* " + introspectedColumn.getRemarks());
        field.addJavaDocLine("*/");
    }

    @Override
    public void addModelClassComment(TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        topLevelClass.addJavaDocLine("/**");
        topLevelClass.addJavaDocLine(" * This class was generated by MyBatis Generator.");
        topLevelClass.addJavaDocLine(" * 表名：" + introspectedTable.getFullyQualifiedTable());
        topLevelClass.addJavaDocLine(" * 表注释：" + introspectedTable.getRemarks());
        topLevelClass.addJavaDocLine(" */");
    }



}
